### ISSUE TITLE
讨论返回列表数据

### ISSUE THREAD

**Issue by alexxd35** [Jiannei/lumen-api-starter#1]
返回列表数据的时候，是不是也把数据包裹在data好一点，不然最外层突然多了个meta和link的字段，看起来有点不协调，我觉得外层无论怎样都保持那几个字段会好一点。

**Comment by Jiannei** [comment]
看来和我一样也是存在一些代码上的「强迫症」，之前在封装的时候也考虑过这一点，因为在某些场景目前的实现会不适用。

比如 Lumen/Laravel 是提供接口服务给**强数据类型**前端（比如安卓或 IOS），对数据结构要求更严格，不仅数据结构必须统一（只返回 data、status、code 和 message），还要求这些参数返回的数据类型也必须固定，比如 status 和 message 必须是字符串、code 必须是整数类型，就不能像我这里返回单条数据的时候 data 是对象类型，返回列表数据的时候是数组类型，而且还会多出 links 和 meta 参数。

目前这样封装是出于**完全**保留 Laravel 的 Api Resource 的返回结构，可以看到在`\\App\\Http\\Response`中的 success 方法中有对 `$data instanceof JsonResource`的判断，Laravel/Lumen 的 api resouce 或 api resouce collection 实际都是 JsonResouce 对象实例，这时的响应结构只是「额外」补充了 status、code和 message，还可以感受「原滋原味」的 Laravel Api Resouce 。

之前封装时有考虑过的结构，返回单条数据时`{"data":{"item":{...},"meta":{...}}},`，返回列表数据时`{"data":{"collection":{...},"meta":{...},"links":{...}}}`，这样最外层的数据结构和类型就统一了，但怎样更多的保留 Laravel 的风格，也是需要考虑的问题。

**Comment by Jiannei** [comment]
> 返回列表数据的时候，是不是也把数据包裹在data好一点，不然最外层突然多了个meta和link的字段，看起来有点不协调，我觉得外层无论怎样都保持那几个字段会好一点。

看来和我一样也是存在一些代码上的「强迫症」，之前在封装的时候也考虑过这一点，因为在某些场景目前的实现会不适用。

比如 Lumen/Laravel 是提供接口服务给强数据类型前端（比如安卓或 IOS），对数据结构要求更严格，不仅数据结构必须统一（只返回 data、status、code 和 message），还要求这些参数返回的数据类型也必须固定，比如 status 和 message 必须是字符串、code 必须是整数类型，就不能像我这里返回单条数据的时候 data 是对象类型，返回列表数据的时候是数组类型，而且还会多出 links 和 meta 参数。

目前这样封装是出于完全保留 Laravel 的 Api Resource 的返回结构，可以看到在\\App\\Http\\Response中的 success 方法中有对 $data instanceof JsonResource的判断，Laravel/Lumen 的 api resouce 或 api resouce collection 实际都是 JsonResouce 对象实例，这时的响应结构只是「额外」补充了 status、code和 message，还可以感受「原滋原味」的 Laravel Api Resouce 。

之前封装时有考虑过的结构，返回单条数据时{"data":{"item":{...},"meta":{...}}},，返回列表数据时{"data":{"collection":{...},"meta":{...},"links":{...}}}，这样最外层的数据结构和类型就统一了，但怎样更多的保留 Laravel 的风格，也是需要考虑的问题。

**Comment by alexxd35** [comment]
> > 返回列表数据的时候，是不是也把数据包裹在data好一点，不然最外层突然多了个meta和link的字段，看起来有点不协调，我觉得外层无论怎样都保持那几个字段会好一点。
> 
> 看来和我一样也是存在一些代码上的「强迫症」，之前在封装的时候也考虑过这一点，因为在某些场景目前的实现会不适用。
> 
> 比如 Lumen/Laravel 是提供接口服务给强数据类型前端（比如安卓或 IOS），对数据结构要求更严格，不仅数据结构必须统一（只返回 data、status、code 和 message），还要求这些参数返回的数据类型也必须固定，比如 status 和 message 必须是字符串、code 必须是整数类型，就不能像我这里返回单条数据的时候 data 是对象类型，返回列表数据的时候是数组类型，而且还会多出 links 和 meta 参数。
> 
> 目前这样封装是出于完全保留 Laravel 的 Api Resource 的返回结构，可以看到在\App\Http\Response中的 success 方法中有对 $data instanceof JsonResource的判断，Laravel/Lumen 的 api resouce 或 api resouce collection 实际都是 JsonResouce 对象实例，这时的响应结构只是「额外」补充了 status、code和 message，还可以感受「原滋原味」的 Laravel Api Resouce 。
> 
> 之前封装时有考虑过的结构，返回单条数据时{"data":{"item":{...},"meta":{...}}},，返回列表数据时{"data":{"collection":{...},"meta":{...},"links":{...}}}，这样最外层的数据结构和类型就统一了，但怎样更多的保留 Laravel 的风格，也是需要考虑的问题。

你好，请问如果我需要将那些数据包到data里面的话，需要改动哪个地方呢？

**Comment by Jiannei** [comment]
> > > 返回列表数据的时候，是不是也把数据包裹在data好一点，不然最外层突然多了个meta和link的字段，看起来有点不协调，我觉得外层无论怎样都保持那几个字段会好一点。
> > 
> > 
> > 看来和我一样也是存在一些代码上的「强迫症」，之前在封装的时候也考虑过这一点，因为在某些场景目前的实现会不适用。
> > 比如 Lumen/Laravel 是提供接口服务给强数据类型前端（比如安卓或 IOS），对数据结构要求更严格，不仅数据结构必须统一（只返回 data、status、code 和 message），还要求这些参数返回的数据类型也必须固定，比如 status 和 message 必须是字符串、code 必须是整数类型，就不能像我这里返回单条数据的时候 data 是对象类型，返回列表数据的时候是数组类型，而且还会多出 links 和 meta 参数。
> > 目前这样封装是出于完全保留 Laravel 的 Api Resource 的返回结构，可以看到在\App\Http\Response中的 success 方法中有对 $data instanceof JsonResource的判断，Laravel/Lumen 的 api resouce 或 api resouce collection 实际都是 JsonResouce 对象实例，这时的响应结构只是「额外」补充了 status、code和 message，还可以感受「原滋原味」的 Laravel Api Resouce 。
> > 之前封装时有考虑过的结构，返回单条数据时{"data":{"item":{...},"meta":{...}}},，返回列表数据时{"data":{"collection":{...},"meta":{...},"links":{...}}}，这样最外层的数据结构和类型就统一了，但怎样更多的保留 Laravel 的风格，也是需要考虑的问题。
> 
> 你好，请问如果我需要将那些数据包到data里面的话，需要改动哪个地方呢？

针对数据分页情况的响应返回，现已经做了改进并提交。

**Comment by alexxd35** [comment]
> > > > 返回列表数据的时候，是不是也把数据包裹在data好一点，不然最外层突然多了个meta和link的字段，看起来有点不协调，我觉得外层无论怎样都保持那几个字段会好一点。
> > > 
> > > 
> > > 看来和我一样也是存在一些代码上的「强迫症」，之前在封装的时候也考虑过这一点，因为在某些场景目前的实现会不适用。
> > > 比如 Lumen/Laravel 是提供接口服务给强数据类型前端（比如安卓或 IOS），对数据结构要求更严格，不仅数据结构必须统一（只返回 data、status、code 和 message），还要求这些参数返回的数据类型也必须固定，比如 status 和 message 必须是字符串、code 必须是整数类型，就不能像我这里返回单条数据的时候 data 是对象类型，返回列表数据的时候是数组类型，而且还会多出 links 和 meta 参数。
> > > 目前这样封装是出于完全保留 Laravel 的 Api Resource 的返回结构，可以看到在\App\Http\Response中的 success 方法中有对 $data instanceof JsonResource的判断，Laravel/Lumen 的 api resouce 或 api resouce collection 实际都是 JsonResouce 对象实例，这时的响应结构只是「额外」补充了 status、code和 message，还可以感受「原滋原味」的 Laravel Api Resouce 。
> > > 之前封装时有考虑过的结构，返回单条数据时{"data":{"item":{...},"meta":{...}}},，返回列表数据时{"data":{"collection":{...},"meta":{...},"links":{...}}}，这样最外层的数据结构和类型就统一了，但怎样更多的保留 Laravel 的风格，也是需要考虑的问题。
> > 
> > 
> > 你好，请问如果我需要将那些数据包到data里面的话，需要改动哪个地方呢？
> 
> 针对数据分页情况的响应返回，现已经做了改进并提交。

我个人觉得那个pagintor键名改成data好一点，虽然这样会双重data，但是data会很明了就让人知道里面是数据。小小建议。

**Comment by Jiannei** [comment]
> > > > > 返回列表数据的时候，是不是也把数据包裹在data好一点，不然最外层突然多了个meta和link的字段，看起来有点不协调，我觉得外层无论怎样都保持那几个字段会好一点。
> > > > 
> > > > 
> > > > 看来和我一样也是存在一些代码上的「强迫症」，之前在封装的时候也考虑过这一点，因为在某些场景目前的实现会不适用。
> > > > 比如 Lumen/Laravel 是提供接口服务给强数据类型前端（比如安卓或 IOS），对数据结构要求更严格，不仅数据结构必须统一（只返回 data、status、code 和 message），还要求这些参数返回的数据类型也必须固定，比如 status 和 message 必须是字符串、code 必须是整数类型，就不能像我这里返回单条数据的时候 data 是对象类型，返回列表数据的时候是数组类型，而且还会多出 links 和 meta 参数。
> > > > 目前这样封装是出于完全保留 Laravel 的 Api Resource 的返回结构，可以看到在\App\Http\Response中的 success 方法中有对 $data instanceof JsonResource的判断，Laravel/Lumen 的 api resouce 或 api resouce collection 实际都是 JsonResouce 对象实例，这时的响应结构只是「额外」补充了 status、code和 message，还可以感受「原滋原味」的 Laravel Api Resouce 。
> > > > 之前封装时有考虑过的结构，返回单条数据时{"data":{"item":{...},"meta":{...}}},，返回列表数据时{"data":{"collection":{...},"meta":{...},"links":{...}}}，这样最外层的数据结构和类型就统一了，但怎样更多的保留 Laravel 的风格，也是需要考虑的问题。
> > > 
> > > 
> > > 你好，请问如果我需要将那些数据包到data里面的话，需要改动哪个地方呢？
> > 
> > 
> > 针对数据分页情况的响应返回，现已经做了改进并提交。
> 
> 我个人觉得那个pagintor键名改成data好一点，虽然这样会双重data，但是data会很明了就让人知道里面是数据。小小建议。

`data.data`  还是 `data.paginator`，或者是 `data.pagination`，又或是`data.list`？

**Comment by alexxd35** [comment]
> > > > > > 返回列表数据的时候，是不是也把数据包裹在data好一点，不然最外层突然多了个meta和link的字段，看起来有点不协调，我觉得外层无论怎样都保持那几个字段会好一点。
> > > > > 
> > > > > 
> > > > > 看来和我一样也是存在一些代码上的「强迫症」，之前在封装的时候也考虑过这一点，因为在某些场景目前的实现会不适用。
> > > > > 比如 Lumen/Laravel 是提供接口服务给强数据类型前端（比如安卓或 IOS），对数据结构要求更严格，不仅数据结构必须统一（只返回 data、status、code 和 message），还要求这些参数返回的数据类型也必须固定，比如 status 和 message 必须是字符串、code 必须是整数类型，就不能像我这里返回单条数据的时候 data 是对象类型，返回列表数据的时候是数组类型，而且还会多出 links 和 meta 参数。
> > > > > 目前这样封装是出于完全保留 Laravel 的 Api Resource 的返回结构，可以看到在\App\Http\Response中的 success 方法中有对 $data instanceof JsonResource的判断，Laravel/Lumen 的 api resouce 或 api resouce collection 实际都是 JsonResouce 对象实例，这时的响应结构只是「额外」补充了 status、code和 message，还可以感受「原滋原味」的 Laravel Api Resouce 。
> > > > > 之前封装时有考虑过的结构，返回单条数据时{"data":{"item":{...},"meta":{...}}},，返回列表数据时{"data":{"collection":{...},"meta":{...},"links":{...}}}，这样最外层的数据结构和类型就统一了，但怎样更多的保留 Laravel 的风格，也是需要考虑的问题。
> > > > 
> > > > 
> > > > 你好，请问如果我需要将那些数据包到data里面的话，需要改动哪个地方呢？
> > > 
> > > 
> > > 针对数据分页情况的响应返回，现已经做了改进并提交。
> > 
> > 
> > 我个人觉得那个pagintor键名改成data好一点，虽然这样会双重data，但是data会很明了就让人知道里面是数据。小小建议。
> 
> `data.data` 还是 `data.paginator`，或者是 `data.pagination`，又或是`data.list`？

个人比较推崇data.data,不过几天没来看了，现在发现你已经改了很多啦

**Comment by Jiannei** [comment]
@alexxd35 是啊，分页的结构还是统一成了 `data.data`，另外支持了响应码和响应消息配置，看看还有没有什么要「添砖加瓦」的地方啊？

**Comment by alexxd35** [comment]
> @alexxd35 是啊，分页的结构还是统一成了 `data.data`，另外支持了响应码和响应消息配置，看看还有没有什么要「添砖加瓦」的地方啊？

$statusTexts = __('response') + HttpResponse::$statusTexts;

我跑了一下，这句话会报错。

**Comment by alexxd35** [comment]
> > @alexxd35 是啊，分页的结构还是统一成了 `data.data`，另外支持了响应码和响应消息配置，看看还有没有什么要「添砖加瓦」的地方啊？
> 
> $statusTexts = __('response') + HttpResponse::$statusTexts;
> 
> 我跑了一下，这句话会报错。

你应该是想将自定义的错误和内置的错误的数组合在一起，但是我按你这个写法跑不成，最后我把自定义的错误放在了一个config文件里面，通过config()来读取

**Comment by Jiannei** [comment]
最终的响应数据结构参考 README 文档说明。

**Comment by Jiannei** [comment]
@alexxd35 新的 issue 中报错信息贴出来一下
