### ISSUE TITLE
自定义响应码和响应描述的问题

### ISSUE THREAD

**Issue by Jiannei** [Jiannei/lumen-api-starter#13]
$statusTexts = __('response') + HttpResponse::$statusTexts;

我跑了一下，这句话会报错。

_Originally posted by @alexxd35 in https://github.com/Jiannei/lumen-api-starter/issues/1#issuecomment-641403617_

**Comment by alexxd35** [comment]
__('response') 会直接返回字符串'response' ,跟后面的数组相加就报错了

**Comment by Jiannei** [comment]
你项目中有`resources/lang/zh-CN/response.php`这个文件吗，或者.env 文件中检查有没有配置`APP_LOCALE=zh-CN`

**Comment by Jiannei** [comment]
@alexxd35 你项目中有`resources/lang/zh-CN/response.php`这个文件吗，或者.env 文件中检查有没有配置`APP_LOCALE=zh-CN`

**Comment by alexxd35** [comment]
应该是APP_LOCALE的配置问题

**Comment by alexxd35** [comment]
可以关闭此issue了，谢谢
