### ISSUE TITLE
Laravel 7 中自定义验证异常响应格式的问题

### ISSUE THREAD

**Issue by alexxd35** [Jiannei/lumen-api-starter#14]
我make了一个request来做表单验证，当参数不符时没有按照统一的返回格式。
返回：
```
{
    "message": "The given data was invalid.",
    "errors": {
        "name": [
            "用户名不能为空"
        ]
    }
}
```

请问需要怎样更改才能将request也支持统一格式？还是说这个系统有特定的定义参数验证的方法呢？
另外我是搬到了laravel中了，不知道有没影响到，还是说这块还没做适配。

**Comment by Jiannei** [comment]
@alexxd35  Laravel  中的验证异常处理与 Lumen 不同，可以参考下面的实现：
```
<?php
// app/Exceptions/Handler.php
namespace App\Exceptions;

use App\Support\Traits\ResponseTrait;
use Illuminate\Auth\AuthenticationException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Validation\ValidationException;
use Throwable;

class Handler extends ExceptionHandler
{
    use ResponseTrait;// 这里引入响应返回时调用的  response

  

  // ....

    /**
     * 定制 ValidationException 响应
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  ValidationException  $exception
     * @return \Illuminate\Http\JsonResponse|void
     */
    protected function invalidJson($request, ValidationException $exception)
    {
        $this->response->fail($exception->getMessage(), 422, $exception->errors());
    }

    protected function unauthenticated($request, AuthenticationException $exception)
    {
        return $request->expectsJson()
            ? $this->response->fail($exception->getMessage(),401)
            : redirect()->guest($exception->redirectTo() ?? route('login'));
    }

    protected function prepareJsonResponse($request, Throwable $e)
    {
        // 要求请求头 header 中包含 /json 或 +json，如：Accept:application/json
        // 或者是 ajax 请求，header 中包含 X-Requested-With：XMLHttpRequest;
        $this->response->fail(
            '',
            $this->isHttpException($e) ? $e->getStatusCode() : 500,
            $this->convertExceptionToArray($e),
            $this->isHttpException($e) ? $e->getHeaders() : [],
            JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES
        );
    }
}

```

注意，这里的版本是 Laravel 7.x，在它以下的版本需要将 `Throwable`替换成`Exception`

**Comment by alexxd35** [comment]
> @alexxd35 Laravel 中的验证异常处理与 Lumen 不同，可以参考下面的实现：
> 
> ```
> <?php
> // app/Exceptions/Handler.php
> namespace App\Exceptions;
> 
> use App\Support\Traits\ResponseTrait;
> use Illuminate\Auth\AuthenticationException;
> use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
> use Illuminate\Validation\ValidationException;
> use Throwable;
> 
> class Handler extends ExceptionHandler
> {
>     use ResponseTrait;// 这里引入响应返回时调用的  response
> 
>   
> 
>   // ....
> 
>     /**
>      * 定制 ValidationException 响应
>      *
>      * @param  \Illuminate\Http\Request  $request
>      * @param  ValidationException  $exception
>      * @return \Illuminate\Http\JsonResponse|void
>      */
>     protected function invalidJson($request, ValidationException $exception)
>     {
>         $this->response->fail($exception->getMessage(), 422, $exception->errors());
>     }
> 
>     protected function unauthenticated($request, AuthenticationException $exception)
>     {
>         return $request->expectsJson()
>             ? $this->response->fail($exception->getMessage(),401)
>             : redirect()->guest($exception->redirectTo() ?? route('login'));
>     }
> 
>     protected function prepareJsonResponse($request, Throwable $e)
>     {
>         // 要求请求头 header 中包含 /json 或 +json，如：Accept:application/json
>         // 或者是 ajax 请求，header 中包含 X-Requested-With：XMLHttpRequest;
>         $this->response->fail(
>             '',
>             $this->isHttpException($e) ? $e->getStatusCode() : 500,
>             $this->convertExceptionToArray($e),
>             $this->isHttpException($e) ? $e->getHeaders() : [],
>             JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES
>         );
>     }
> }
> ```
> 
> 注意，这里的版本是 Laravel 7.x，在它以下的版本需要将 `Throwable`替换成`Exception`

可以了，谢谢。
