### ISSUE TITLE
[建议]jenssegers/mongodb 换成不必要依赖mongo的C扩展的组件

### ISSUE THREAD

**Issue by chunpat** [Jiannei/lumen-api-starter#23]
不知道有没有操作mongodb 完全基于纯php的组件，像redis的predis组件：https://github.com/nrk/predis

**Comment by Jiannei** [comment]
> 不知道有没有操作mongodb 完全基于纯php的组件，像redis的predis组件：https://github.com/nrk/predis

目前似乎没有更好的替代组件 :)
