### ISSUE TITLE
枚举转换出现问题

### ISSUE THREAD

**Issue by chunpat** [Jiannei/lumen-api-starter#24]
请求Post /authorization，结果：
```
{
    "status": "fail",
    "code": 500,
    "message": "Internal Server Error",
    "data": {
        "message": "Undefined offset: 200102",
        "exception": "ErrorException",
        "file": "/Volumes/work/www/zzhpeng/lumen-api-starter/app/Repositories/Enums/ResponseCodeEnum.php",
        "line": 52,
        "trace": [
            {
                "file": "/Volumes/work/www/zzhpeng/lumen-api-starter/app/Repositories/Enums/ResponseCodeEnum.php",
                "line": 52,
                "function": "Laravel\\Lumen\\Concerns\\{closure}",
                "class": "Laravel\\Lumen\\Application",
                "type": "->"
            },
            {
    ......
```

**Comment by Jiannei** [comment]
感谢反馈，有两种处理方式：

1. `.env` 文件中配置 `APP_LOCALE=zh-CN`
2. `resources/lang/en/enums.php` 文件中补充英文 ResponseCodeEnum 中定义的常量描述

**Comment by Jiannei** [comment]
> 请求Post /authorization，结果：
> 
> ```
> {
>     "status": "fail",
>     "code": 500,
>     "message": "Internal Server Error",
>     "data": {
>         "message": "Undefined offset: 200102",
>         "exception": "ErrorException",
>         "file": "/Volumes/work/www/zzhpeng/lumen-api-starter/app/Repositories/Enums/ResponseCodeEnum.php",
>         "line": 52,
>         "trace": [
>             {
>                 "file": "/Volumes/work/www/zzhpeng/lumen-api-starter/app/Repositories/Enums/ResponseCodeEnum.php",
>                 "line": 52,
>                 "function": "Laravel\\Lumen\\Concerns\\{closure}",
>                 "class": "Laravel\\Lumen\\Application",
>                 "type": "->"
>             },
>             {
>     ......
> ```

感谢反馈，有两种处理方式：

1. `.env` 文件中配置 `APP_LOCALE=zh-CN`
2. `resources/lang/en/enums.php` 文件中补充英文 ResponseCodeEnum 中定义的常量描述
