### ISSUE TITLE
Laravel 7 中的 ValidationException 校验异常，没有返回具体的错误信息

### ISSUE THREAD

**Issue by nicesome** [Jiannei/lumen-api-starter#27]
使用 l5 验证类时，抛出异常的详细错误信息没有返回：
```
$this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_UPDATE);
```

目前返回内容：
```
{
	"status": "fail",
	"code": 500,
	"message": "Internal Server Error",
	"data": {
		"message": "Server Error"
	}
}
```

**Comment by nicesome** [comment]
目前已解决，解决方案如下：
```
use Prettus\Validator\Exceptions\ValidatorException;

try {
    $this->validator->with($request->all())->passesOrFail();
} catch (ValidatorException $e) {
    $this->response->fail($e->getMessageBag()->first());
}
```

**Comment by Jiannei** [comment]
> 临时解决方案如下：
> 
> ```
> use Prettus\Validator\Exceptions\ValidatorException;
> 
> try {
>     $this->validator->with($request->all())->passesOrFail();
> } catch (ValidatorException $e) {
>     $this->response->fail($e->getMessageBag()->first());
> }
> ```

优秀 👍 

是因为没有对 L5-repository  的 ValidatorException 异常进行捕获，这就加上。

**Comment by nicesome** [comment]
> > 临时解决方案如下：
> > ```
> > use Prettus\Validator\Exceptions\ValidatorException;
> > 
> > try {
> >     $this->validator->with($request->all())->passesOrFail();
> > } catch (ValidatorException $e) {
> >     $this->response->fail($e->getMessageBag()->first());
> > }
> > ```
> 
> 优秀 👍
> 
> 是因为没有对 L5-repository 的 ValidatorException 异常进行捕获，这就加上。

🐂🍺
作者回复处理效率甚快！
