### ISSUE TITLE
ResponseCodeEnum 自定义错误码该如何使用？

### ISSUE THREAD

**Issue by nicesome** [Jiannei/lumen-api-starter#28]
Q1：能否单独一个类？
如果过多的错误码堆积在一起就不好解藕了。

Q2：目前只能在 ResponseCodeEnum 定义，后期有封装么？

**Comment by Jiannei** [comment]
> Q1：能否单独一个类？
> 如果过多的错误码堆积在一起就不好解藕了。
> 
> Q2：目前只能在 ResponseCodeEnum 定义，后期有封装么？

（如果有需要的话）可以简单地继承 ResponseCodeEnum，然后根据业务需求定义响应码。比如 SystemResponseCodeEnum 等。

使用的话主要是在抛异常 `abort(ResponseCodeEnum::SYSTEM_ERROR, $e->getMessage());` 或者 Controller  中通过 `$this->response`调用 success、fail 等方法时指定响应码。

**Comment by Vinoctis** [comment]
abort(自定义的code) 会报 InvalidArgumentException The HTTP status code "*" is not valid.
