### ISSUE TITLE
[建议]一键生成通用的模板

### ISSUE THREAD

**Issue by chunpat** [Jiannei/lumen-api-starter#35]
Repository&service结构要弄好多文件，开一个新的模块，要一个一个创建，应该弄个一键生成的通用模板，这样就很爽！！

**Comment by Jiannei** [comment]
> Repository&service结构要弄好多文件，开一个新的模块，要一个一个创建，应该弄个一键生成的通用模板，这样就很爽！！

我想想怎么弄，或者要不你提一个 pull request 过来  :sunglasses:

**Comment by chunpat** [comment]
@Jiannei 好，我尝试下

**Comment by chunpat** [comment]
@Jiannei https://github.com/chunpat/lumen-api-starter-generator，弄了个初版，指教指教

**Comment by Jiannei** [comment]
@chunpat 看着很丰富，晚点试用下 👍
