### ISSUE TITLE
请问可以做一个laravel版本的吗

### ISSUE THREAD

**Issue by alexxd35** [Jiannei/lumen-api-starter#51]
我尝试搬过去laravel，但是发现现在更新了挺多

**Comment by alexxd35** [comment]
https://github.com/alexxd35/laravel-api-starter

已经搬了一些过去，可以帮忙看看哪里还有错吗，我觉得主要是exception handler那里还有providers那里。因为我在app.php添加那个eloquentuserproviers就会报错，现在只能注释了

**Comment by Jiannei** [comment]
@alexxd35 好的，安排一下。

**Comment by Jiannei** [comment]
@alexxd35  已支持 [laravel-api-starter](https://github.com/Jiannei/laravel-api-starter) :tada:
